version: '3.7'
services:
  postgresql:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=imed
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=imed
    volumes:
      - pg_data:/var/lib/postgresql/data
  django:
    container_name: django
    build: ./docker/python
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    links:
      - postgresql
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - 8888:80
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - django
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
volumes:
  pg_data:
