# Generated by Django 2.1.15 on 2020-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Matrícula'),
        ),
    ]
