# Generated by Django 3.0.7 on 2020-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201110_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacao',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
