# Generated by Django 3.0.7 on 2020-11-10 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20201110_0221'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.DecimalField(decimal_places=2, max_digits=5)),
                ('localidade', models.CharField(max_length=255, null=True, verbose_name='Localidade')),
                ('advogados', models.ManyToManyField(related_name='user_advogado', related_query_name='user_advogado', to=settings.AUTH_USER_MODEL, verbose_name='Advogados')),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Simulacao')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ParteAutora',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=5000, verbose_name='Descricao')),
                ('cpf', models.CharField(max_length=5000, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=5000, verbose_name='CNPJ')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo.Processo')),
            ],
            options={
                'verbose_name': 'Parte Autora',
                'verbose_name_plural': 'Partes Autoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=5000, verbose_name='Descricao')),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo.Processo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='EtapaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='uploads/documentos/')),
                ('sigilo', models.BooleanField(default=False, verbose_name='Nome')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Etapa')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo.Processo')),
            ],
            options={
                'verbose_name': 'Etapa Documento',
                'verbose_name_plural': 'Etapas Documentos',
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='preocesso',
            field=models.ManyToManyField(related_name='etapa_processo', related_query_name='etapa_processo', to='processo.Processo', verbose_name='Processo Etapa'),
        ),
    ]
