# Generated by Django 3.0.7 on 2020-11-17 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Assunto')),
            ],
            options={
                'verbose_name': 'Assunto',
                'verbose_name_plural': 'Assuntos',
            },
        ),
        migrations.CreateModel(
            name='ClasseProcedural',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Classe Procedural',
                'verbose_name_plural': 'Classes Procedurais',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='antecipacao_tutela',
            field=models.BooleanField(default=False, verbose_name='Requer Liminar/Antecipação de Tutela'),
        ),
        migrations.AddField(
            model_name='processo',
            name='area',
            field=models.CharField(choices=[('Cível - Ações Coletivas', 'Cível - Ações Coletivas'), ('Cível - Cível', 'Cível - Cível'), ('Cível - Empresas', 'Cível - Empresas'), ('Cível - Recuperação Juridical e Falência', 'Cível - Recuperação Juridical e Falência'), ('Cível - Registros Públicos', 'Cível - Registros Públicos'), ('Familia/Sucessões/Curatelas', 'Familia/Sucessões/Curatelas')], max_length=500, null=True, verbose_name='ÁREA'),
        ),
        migrations.AddField(
            model_name='processo',
            name='competencia',
            field=models.CharField(max_length=255, null=True, verbose_name='Competência'),
        ),
        migrations.AddField(
            model_name='processo',
            name='consiliacao',
            field=models.BooleanField(default=False, verbose_name='Manifesto que não tenho interesse em conciliar (art. 334, paragrafo 5°CPC)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='nivel_sigilo',
            field=models.CharField(choices=[('0', 'Sem sigilo (Nível 0)'), ('1', 'Segredo de Justiça (Nível 1)')], max_length=500, null=True, verbose_name='Sigilo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='parte_autora',
            field=models.ManyToManyField(blank=True, related_name='parte_autora', to=settings.AUTH_USER_MODEL, verbose_name='Parte Autora'),
        ),
        migrations.AddField(
            model_name='processo',
            name='parte_reus',
            field=models.ManyToManyField(blank=True, related_name='parte_reus', to=settings.AUTH_USER_MODEL, verbose_name='Parte Réus'),
        ),
        migrations.AddField(
            model_name='processo',
            name='rito',
            field=models.CharField(choices=[('RITO_ORDINÁRIO(COMUM)', 'RITO ORDINÁRIO (COMUM)')], max_length=500, null=True, verbose_name='Rito'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tramitação_crianca',
            field=models.BooleanField(default=False, verbose_name='Requer prioridade de tramitação - Criança e Adolescente'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tramitação_deficiencia',
            field=models.BooleanField(default=False, verbose_name='Requer prioridade de tramitação - Pessoa com deficiência'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tramitação_doenca',
            field=models.BooleanField(default=False, verbose_name='Requer prioridade de tramitação - Doença grave'),
        ),
        migrations.AddField(
            model_name='processo',
            name='tramitação_idoso',
            field=models.BooleanField(default=False, verbose_name='Requer prioridade de tramitação - Idoso'),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor_da_causa',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogados',
            field=models.ManyToManyField(blank=True, related_name='user_advogado', related_query_name='user_advogado', to=settings.AUTH_USER_MODEL, verbose_name='Advogados'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='localidade',
            field=models.CharField(max_length=255, null=True, verbose_name='Desejo entrar com ação em'),
        ),
        migrations.AddField(
            model_name='processo',
            name='assunto_principal',
            field=models.ManyToManyField(blank=True, related_name='assuntos_principais', to='processo.Assunto', verbose_name='Assunto Principal'),
        ),
        migrations.AddField(
            model_name='processo',
            name='assuntos',
            field=models.ManyToManyField(blank=True, related_name='assuntos_secundarios', to='processo.Assunto', verbose_name='Assuntos'),
        ),
        migrations.AddField(
            model_name='processo',
            name='classe_procedural',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processo.ClasseProcedural'),
        ),
    ]
