# Generated by Django 3.0.7 on 2020-11-23 03:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0002_auto_20201117_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='uploads/documentos/')),
                ('tipo', models.CharField(max_length=255, verbose_name='Nome')),
                ('sigilo', models.BooleanField(default=False, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='processo',
            name='documentos',
            field=models.ManyToManyField(blank=True, related_name='processo_documentos', to='processo.Documentos', verbose_name='Documentos'),
        ),
    ]
