# Generated by Django 3.0.7 on 2020-11-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0003_auto_20201123_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processo',
            options={'ordering': ['id'], 'verbose_name': 'Processo', 'verbose_name_plural': 'Processos'},
        ),
        migrations.RemoveField(
            model_name='processo',
            name='numero',
        ),
    ]
