# Generated by Django 3.0.7 on 2020-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo', '0004_auto_20201123_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='sigilo',
            field=models.BooleanField(default=False, verbose_name='Sigilo'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='tipo',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
    ]
